# Generated by Django 2.0.3 on 2018-03-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catcollector', '0002_cat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
